"""
This script draws a set of squares based on inputs based to it

@author: Amin Alhashim (aalhashi@macalester.edu)
@author: Susan Fox
"""

import turtle
colors = ['cyan', 'purple', 'pink', 'blue']
sqSize = 100
scr = turtle.Screen()
dotTurt = turtle.Turtle()
dotTurt.up()
dotTurt.backward(2 * sqSize)
dotTurt.down()
dotTurt.color(colors[0])
dotTurt.begin_fill()
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.end_fill()
dotTurt.forward(sqSize)
dotTurt.color(colors[1])
dotTurt.begin_fill()
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.end_fill()
dotTurt.forward(sqSize)
dotTurt.color(colors[2])
dotTurt.begin_fill()
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.end_fill()
dotTurt.forward(sqSize)
dotTurt.color(colors[3])
dotTurt.begin_fill()
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.forward(sqSize)
dotTurt.left(90)
dotTurt.end_fill()
scr.exitonclick()
